steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_GOOGLE_MAPS_API_KEY}"
      - "-t"
      - "${_IMAGE}"
      - "."

images:
  - "${_IMAGE}"

substitutions:
  _IMAGE: "us-central1-docker.pkg.dev/$PROJECT_ID/nextjs/app"
  _GOOGLE_MAPS_API_KEY: ""